<?php

// defined('XOOPS_ROOT_PATH') || die('Restricted access');

$GLOBALS['myalbum_assign_globals'] = [
    'lang_total'           => _ALBM_CAPTION_TOTAL,
    'mod_url'              => $mod_url,
    'mod_copyright'        => $mod_copyright,
    'lang_latest_list'     => _ALBM_LATESTLIST,
    'lang_descriptionc'    => _ALBM_DESCRIPTIONC,
    'lang_lastupdatec'     => _ALBM_LASTUPDATEC,
    'lang_submitter'       => _ALBM_SUBMITTER,
    'lang_hitsc'           => _ALBM_HITSC,
    'lang_commentsc'       => _ALBM_COMMENTSC,
    'lang_new'             => _ALBM_NEW,
    'lang_updated'         => _ALBM_UPDATED,
    'lang_popular'         => _ALBM_POPULAR,
    'lang_ratethisphoto'   => _ALBM_RATETHISPHOTO,
    'lang_editthisphoto'   => _ALBM_EDITTHISPHOTO,
    'lang_deletethisphoto' => _ALBM_DELETE_THIS_PHOTO,
    'lang_guestname'       => _ALBM_CAPTION_GUESTNAME,
    'lang_category'        => _ALBM_CAPTION_CATEGORY,
    'lang_nomatch'         => _ALBM_NOMATCH,
    'lang_directcatsel'    => _ALBM_DIRECTCATSEL,
    'photos_url'           => $photos_url,
    'thumbs_url'           => $thumbs_url,
    'thumbsize'            => $myalbum_thumbsize,
    'colsoftableview'      => $myalbum_colsoftableview,
    'canrateview'          => $GLOBALS['global_perms'] && GPERM_RATEVIEW,
    'canratevote'          => $GLOBALS['global_perms'] && GPERM_RATEVOTE,
];

//Gnavi
$gnavi_assign_globals = [
    'mod_url'            => $mod_url,
    'mod_copyright'      => $mod_copyright,
    'lang_submitter'     => _MD_GNAV_C_SUBMITTER,
    'lang_hitsc'         => _MD_GNAV_C_RAT_HITSC,
    'lang_commentsc'     => _MD_GNAV_CMT_COMMENTSC,
    'lang_new'           => _MD_GNAV_C_NEW,
    'lang_updated'       => _MD_GNAV_C_UPDATED,
    'lang_popular'       => _MD_GNAV_C_POPULAR,
    'lang_ratethisphoto' => _MD_GNAV_RAT_RATETHISPHOTO,
    'lang_editthisphoto' => _MD_GNAV_SMT_EDITITEM,
    'lang_guestname'     => _GNAV_CAPTION_GUESTNAME,
    'lang_category'      => _GNAV_CAPTION_CATEGORY,
    'lang_nomatch'       => _MD_GNAV_MSG_NOMATCH,
    'lang_directcatsel'  => _MD_GNAV_CAT_DIRECTCATSEL,
    'lang_markerlist'    => _MD_GNAV_MAP_MARKERLIST,
    'lang_loading'       => _MD_GNAV_MAP_LOADING,
    'lang_lat'           => _MD_GNAV_MAP_LAT,
    'lang_lng'           => _MD_GNAV_MAP_LNG,
    'lang_zoom'          => _MD_GNAV_MAP_ZOOM,
    'lang_movepid'       => _MD_GNAV_CAT_MOVE_PARENT,
    'photos_url'         => $photos_url,
    'thumbs_url'         => $thumbs_url,
    'thumbsize'          => $gnavi_thumbsize,
    'colsoftableview'    => $gnavi_colsoftableview,
    'colstbl_width'      => $gnavi_colsoftableview ? 'width:' . (int)(100 / $gnavi_colsoftableview) . '%;' : '',
    'canrateview'        => $global_perms & GNAV_GPERM_RATEVIEW,
    'canratevote'        => $global_perms & GNAV_GPERM_RATEVOTE,
    'home'               => _MD_GNAV_WEBTOP,
    'canvote'            => $gnavi_usevote,
    'comment_dirname'    => $gnavi_comment_dirname,
    'comment_forum_id'   => $gnavi_comment_forum_id,
    'comment_view'       => $gnavi_comment_view,
    'mydirname'          => $mydirname,
    'am_cat_edit'        => $isadmin ? _MD_GNAV_CAT_EDIT : '',
    'lang_itemlist'      => _MD_GNAV_CAT_ITEMLIST,
    'lang_url'           => _MD_GNAV_ITM_URL,
    'lang_tel'           => _MD_GNAV_ITM_TEL,
    'lang_fax'           => _MD_GNAV_ITM_FAX,
    'lang_zip'           => _MD_GNAV_ITM_ZIP,
    'lang_address'       => _MD_GNAV_ITM_ADDRESS,
    'lang_map'           => _MD_GNAV_MAP,
    'lang_readmore'      => _MD_GNAV_NAV_READMORE,
    'lang_print'         => _MD_GNAV_ITM_PRINT,
    'lang_top_link'      => sprintf(_MD_GNAV_MOBILE_TOP, $xoopsModule->getVar('name')),
];
